### ISSUE TITLE
Typo in flavor.toml

### ISSUE THREAD

**Issue by arnoj** [BennyOe/tokyo-night.yazi#2]
Thanks for the flavor. Just wanted to quickly let you know there's a small typo in the color here (double number sign).

https://github.com/BennyOe/tokyo-night.yazi/blob/d371a8741f64ad395111e66f423c8f940624fd67/flavor.toml#L56

**Comment by BennyOe** [comment]
Thanks for the notice. I corrected the typo. ;)
