### ISSUE TITLE
Poor contrast on 'pills'

### ISSUE THREAD

**Issue by leonlonsdale** [BennyOe/tokyo-night.yazi#6]
The colours on the 'pills' are somewhat unreadable due to poor contrast:

<img width="776" alt="Screenshot 2024-12-29 at 18 46 51" src="https://github.com/user-attachments/assets/fac02260-be14-42a0-8706-e3eba9ed4314" />

**Comment by Zeioth** [comment]
@ionztorm this is related to issue:
https://github.com/BennyOe/tokyo-night.yazi/issues/3

And solved on the PR:
https://github.com/BennyOe/tokyo-night.yazi/pull/4
